export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const POST_LOADING = 'POST_LOADING';
export const CANCEL_ABLETST = 'CANCEL_ABLETST';
